In [1]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense,Activation,InputLayer
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.models import Sequential 
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
x_train = x_train.reshape(-1, 28 * 28).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28 * 28).astype("float32") / 255.0
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000, 784)
(60000,)


In [3]:
def fully_connected_layer():
  model = Sequential()
  
  model.add(InputLayer(x_train.shape[1]))
  model.add(Dense(100,activation = 'relu',name = 'hidden_layer'))
  model.add(Dense(10,activation = 'softmax',name = 'output_layer'))

  model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),loss=keras.losses.SparseCategoricalCrossentropy(),metrics=["accuracy"])

  return model

In [4]:
model = fully_connected_layer()
print(model.summary())
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=1)
test_loss , test_acc = model.evaluate(x_test, y_test, batch_size=32, verbose=2)
print("test_loss: ",test_loss)
print("test accuracy: ",test_acc)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
hidden_layer (Dense)         (None, 100)               78500     
_________________________________________________________________
output_layer (Dense)         (None, 10)                1010      
Total params: 79,510
Trainable params: 79,510
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2701 - accuracy: 0.9245
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1220 - accuracy: 0.9646
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0846 - accuracy: 0.9749
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0663 - accuracy: 0.9801
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0514 - accuracy: 0.9844
313/

In [5]:
y_pred = model.predict(x_test,batch_size=32)
y_pred = np.argmax(y_pred,axis=-1)
test_acc = metrics.accuracy_score(y_test,y_pred)
precision = metrics.precision_score(y_test,y_pred,average = 'micro')
recall = metrics.recall_score(y_test,y_pred,average = 'micro')
f1 = metrics.f1_score(y_test,y_pred,average = 'micro')
print(metrics.confusion_matrix(y_test,y_pred))

fully_connected_reports = {'test_acc':test_acc,'precision':precision,'recall':recall,'f1_score':f1}

[[ 958    0    1    0    5    3    4    4    2    3]
 [   0 1126    2    2    0    1    3    0    1    0]
 [   2    0 1012    2    3    0    2    6    5    0]
 [   0    0    2  988    0    6    0    7    5    2]
 [   0    0    2    0  968    0    4    1    0    7]
 [   2    1    0    4    2  873    4    1    3    2]
 [   1    2    1    1    8    4  941    0    0    0]
 [   0    5    8    4    1    0    0 1002    0    8]
 [   3    0    5    8   12    6    5    5  926    4]
 [   0    5    0    4   12    1    1    3    1  982]]


In [6]:
def neural_net():
  model = Sequential()
  model.add(InputLayer(x_train.shape[1]))
  
  model.add(Dense(10,activation = 'relu',name = 'hidden_layer1'))
  model.add(Dense(10,activation = 'relu',name = 'hidden_layer2'))
  model.add(Dense(10,activation = 'relu',name = 'hidden_layer3'))
  model.add(Dense(10,activation = 'relu',name = 'hidden_layer4'))
  model.add(Dense(10,activation = 'relu',name = 'hidden_layer5'))
  model.add(Dense(10,activation = 'relu',name = 'hidden_layer6'))
  model.add(Dense(10,activation = 'relu',name = 'hidden_layer7'))
  model.add(Dense(10,activation = 'relu',name = 'hidden_layer8'))
  model.add(Dense(10,activation = 'relu',name = 'hidden_layer9'))
  model.add(Dense(10,activation = 'relu',name = 'hidden_layer10'))
  model.add(Dense(10,activation = 'softmax',name = 'output_layer'))

  model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),loss=keras.losses.SparseCategoricalCrossentropy(),metrics=["accuracy"])

  return model

In [14]:
model = neural_net()
print(model.summary())
model.fit(x_train, y_train, batch_size=32, epochs=30, verbose=1)
test_loss , test_acc = model.evaluate(x_test, y_test, batch_size=32, verbose=2)
print("test_loss: ",test_loss)
print("test accuracy: ",test_acc)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
hidden_layer1 (Dense)        (None, 10)                7850      
_________________________________________________________________
hidden_layer2 (Dense)        (None, 10)                110       
_________________________________________________________________
hidden_layer3 (Dense)        (None, 10)                110       
_________________________________________________________________
hidden_layer4 (Dense)        (None, 10)                110       
_________________________________________________________________
hidden_layer5 (Dense)        (None, 10)                110       
_________________________________________________________________
hidden_layer6 (Dense)        (None, 10)                110       
_________________________________________________________________
hidden_layer7 (Dense)        (None, 10)               

In [15]:
y_pred = model.predict(x_test,batch_size=32)
y_pred = np.argmax(y_pred,axis=-1)
test_acc = metrics.accuracy_score(y_test,y_pred)
precision = metrics.precision_score(y_test,y_pred,average = 'micro')
recall = metrics.recall_score(y_test,y_pred,average = 'micro')
f1 = metrics.f1_score(y_test,y_pred,average = 'micro')
print(metrics.confusion_matrix(y_test,y_pred))

neuralnet_reports = {'test_acc':test_acc,'precision':precision,'recall':recall,'f1_score':f1}

[[ 941    0    6    0    0    4    8    5   14    2]
 [   0 1116    4    2    0    0    2    5    6    0]
 [  20    3  939   11   16    5    3    7   25    3]
 [   1    1   56  860    0   48    0    9   29    6]
 [   0    3    7    0  941    2    4    3    9   13]
 [  13    2    2   38    3  755   14    0   59    6]
 [  11    2    1    0   11    7  921    0    5    0]
 [   1   12   22    6    5    0    0  959    5   18]
 [   7    3    7   12    6   11    3    3  903   19]
 [   5    5    0    7   37    6    1   16   31  901]]


In [16]:
df = pd.DataFrame(columns = list(fully_connected_reports.keys()),index = ['fully connected','deep neural network'])

In [17]:
df.loc['fully connected'] = fully_connected_reports
df.loc['deep neural network'] = neuralnet_reports
df

test_acc precision  recall f1_score
fully connected       0.9776    0.9776  0.9776   0.9776
deep neural network   0.9236    0.9236  0.9236   0.9236

It can be observed that the test accuracy of fully connected layer with one hidden layer is more than that of deep neural network. so adding dense layer with relu activation isn't learning more features.

In [11]:
def feature_classifier(model,layer_no):
  extract = Model(model.inputs, model.layers[layer_no-1].output)
  features = extract.predict(x_train)
  test_features = extract.predict(x_test)
  cls = KNeighborsClassifier(n_neighbors=5)
  cls.fit(features,y_train)
  y_pred = cls.predict(test_features)
  print("test accuracy for {}th layer features: ".format(layer_no),metrics.accuracy_score(y_test,y_pred))
  

In [12]:
feature_classifier(model,5)
feature_classifier(model,7)
feature_classifier(model,10)

test accuracy for 5th layer features:  0.9229
test accuracy for 7th layer features:  0.923
test accuracy for 10th layer features:  0.924


Test accuracy from feature extracted from 5th, 7th and 10th layer are almost equal. so adding more hidden layers isn't much useful.